_target_: dmsp.models.trainers.sad_emilie.SadEmilie
device: cuda
lookback: 3
noise_model:
    _target_: dmsp.models.noise.gaussian.GaussianNoise
    noise_size: 10
stream_data: false
optimizer_cls: torch.optim.Adam
k: 5
n_train_generated_samples: 30
use_log_loss_for_backprop: true
prediction_model: ??? 
