_target_: dmsp.models.trainers.stochasticity_loss_trainer.StochasticityLossTrainer
device: mps
lookback: 3
prediction_model:
    _target_: experiment_lab.common.networks.create_mlp_network
    layer_sizes:
        - 3
        - 3
        - 1
    layer_activations:
        _target_: torch.nn.LeakyReLU
        negative_slope: 0.01
    final_activation: null
optimizer_cls: torch.optim.Adam