_target_: dmsp.models.trainers.gan_trainer.ConditionalGANTrainer
device: cuda
lookback: 10
generator:
    _target_: experiment_lab.common.networks.create_aggregated_network
    module_lst:
        - _target_: torch.nn.Identity
        - _target_: torch.nn.Identity
    aggregator:
        _target_: hydra.utils.get_method
        path: torch.cat
    output_module:
        _target_: experiment_lab.common.networks.create_mlp_network
        layer_sizes:
            - "${eval: ${trainer.lookback} * ${data_dim} + ${trainer.noise_model.noise_size}}"
            - 5
            - 1
        layer_activations:
            _target_: torch.nn.LeakyReLU
            negative_slope: 0.01
        final_activation: null
discriminator:
    _target_: experiment_lab.common.networks.create_aggregated_network
    module_lst:
        - _target_: torch.nn.Identity
        - _target_: torch.nn.Identity
    aggregator:
        _target_: hydra.utils.get_method
        path: torch.cat
    output_module:
        _target_: experiment_lab.common.networks.create_mlp_network
        layer_sizes:
            - "${eval: ${trainer.lookback} * ${data_dim} + ${trainer.discriminator_lookforward}}"
            - 5
            - 1
        layer_activations:
            _target_: torch.nn.LeakyReLU
            negative_slope: 0.01
        final_activation: null
noise_model:
    _target_: dmsp.models.noise.gaussian.GaussianNoise
    noise_size: 10
discriminator_lookforward: 5
stream_data: false
optimizer_cls: torch.optim.Adam
optimizer_kwargs:
    lr: 0.001
discriminator_steps_per_generator_step: 50
generator_prediction_loss_weight: 1
