_target_: experiment_lab.common.networks.create_aggregated_network
module_lst:
    - _target_: torch.nn.Identity
    - _target_: torch.nn.Identity
aggregator:
    _target_: hydra.utils.get_method
    path: torch.cat
output_module:
    _target_: experiment_lab.common.networks.create_mlp_network
    layer_sizes:
        - "${eval: ${trainer.lookback} * ${data_dim} + ${trainer.discriminator_lookforward} * ${data_dim}}"
        - 50
        - 1
    layer_activations:
        _target_: torch.nn.LeakyReLU
        negative_slope: 0.01
    final_activation:
        _target_: torch.nn.Sigmoid