_target_: dmsp.datasets.finance.yfinance_loader.YFinanceLoader
symbols:
  - SPY
  - QQQ
  - AMZN
  - MSFT
  - AAPL
  # - WM
  # - STEEL
  # - VIX
  # - USDJPY=X
  # - JPYUSD=X
download_kwargs:
  - start: 2010-01-01
    end: 2023-12-31
    interval: 1d
columns:
  - Adj Close
normalize_by_first_price: true
query_separately: true
