_target_: dmsp.datasets.finance.yfinance_loader.YFinanceLoader
symbols:
  - SPY
  - AMZN
  - QQQ
  - MSFT
download_kwargs:
  - start: 2022-01-01
    end: 2022-12-31
    interval: 1d
  - start: 2019-01-01
    end: 2021-12-31
    interval: 1d
  - start: 2023-01-01
    end: 2023-12-31
    interval: 1d
columns:
  - Adj Close
  - Volume
normalize_by_first_price: true
