trainer:
    device: mps
hydra:
    verbose: true
wandb:
    mode: disabled
defaults:
    - toy_experiment
    # - funky_wiener_experiment
    # - yfinance_experiment
    # - lake_experiment
    - _self_
