experiment_name: solar_experiment
load_model_from_path: false
train_model: true
eval_model: true
visualize_samples:
    n_row_samples: 2
    n_col_samples: 3
    traj_length: 50
    sample_from_lookback: 40
    plot_subset_features: null
n_epochs: 100
n_epochs_per_save: 10
defaults:
    - dmsp
    - data_loader/solar
    - trainer/solar_slt
    - _self_
