experiment_name: toy_experiment
load_model_from_path: false
train_model: true
eval_model: true
visualize_samples:
    n_samples: 6
    traj_length: 50
    sample_from_lookback: 20
    plot_subset_features: null
n_epochs: 2500
n_epochs_per_save: 10000
defaults:
    - dmsp
    - data_loader/toy
    - trainer/tiny_slt
    - _self_
