experiment_name: wiener_experiment
load_model_from_path: false
train_model: true
eval_model: true
visualize_samples:
    n_samples: 6
    traj_length: 4000
    sample_from_lookback: 1000
    plot_subset_features: null
    fig_size_row_multiplier: 30
    fig_size_col_multiplier: 1
n_epochs: 2500
n_epochs_per_save: 10000
data_dim: 1
defaults:
    - dmsp
    - data_loader/wiener
    - trainer/big_slt
    - _self_
