experiment_name: yfinance_experiment
load_model_from_path: false
train_model: true
eval_model: true
visualize_samples:
    n_samples: 10
    traj_length: 100
    sample_from_lookback: 50
    plot_subset_features: null
    fig_size_row_multiplier: 8
    fig_size_col_multiplier: 4
n_epochs: 150
n_epochs_per_save: 30
data_dim: 10
defaults:
    - dmsp
    - data_loader/yfinance
    - _self_
